### ISSUE TITLE
Better error handling.

### ISSUE THREAD

**Issue by richburdon** [alecthomas/flask_injector#12]
When something isn't bound the error message doesn't help you find what it is. E.g., below.

TypeError: __init__() takes exactly 2 arguments (1 given)

It would be really useful if the KEY or type that is not bound is somewhere in the error. It would also be useful to have a mechanism to list all of the bindings.

**Comment by jstasiak** [comment]
@richburdon Can you share the source code to reproduce this and what versions of Injector and Flask-Injector are you using?
