### ISSUE TITLE
Support implicit injections via annotations

### ISSUE THREAD

**Issue by roganov** [alecthomas/flask_injector#16]
Injector supports implicit via annotations using `use_annotations=True` flag (see https://github.com/alecthomas/injector/blob/master/injector_test_py3.py), would be nice to have this in flask_injector.

**Comment by alecthomas** [comment]
I believe you can already do this by passing a pre-constructed `Injector` instance to the `FlaskInjector` constructor.

**Comment by roganov** [comment]
@alecthomas Sorry, it seems that my issue was that `injector` doesn't inject functions with annotations-based dependencies. Class-based views seem to work.

**Comment by alecthomas** [comment]
That's a bit surprising, I'll take a look.

**Comment by jstasiak** [comment]
Yeah, well, Injector is not at fault here, the Flask/Injector integration layer does some things manually though and it doesn't do annotations at the moment - I have a working patch though so I'll release it after some cleanup.

**Comment by roganov** [comment]
Haven't had a chance to try out yet, but it seems that the issue is resolve. Thanks @jstasiak!
