### ISSUE TITLE
Flask extension support relies on pattern deprecated by Injector

### ISSUE THREAD

**Issue by gavinmh** [alecthomas/flask_injector#17]
Hi all,

Injector has deprecated support for injecting into `Module.configure()` (https://github.com/alecthomas/injector/issues/31). This was the recommended pattern for working with Flask extensions (https://github.com/alecthomas/flask_injector#supporting-flask-extensions). Do you have any other recommendations for working with Flask extensions?

Thanks,
Gavin

**Comment by gavinmh** [comment]
Never mind, the following works:
```
class ConfigurationModule(Module):

    def __init__(self, app):
        self.app = app

    def configure(self, binder):
        api = Api(self.app)
        api.add_resource(MyResource, '/foo')
        binder.bind(Foo, to=Foo(), scope=singleton)
        binder.bind(Api, to=api, scope=singleton)


def main():
    app = Flask(__name__)
    FlaskInjector(app=app, modules=[ConfigurationModule(app)])
    app.run(debug=True)
```

**Comment by pdonorio** [comment]
Thanks for opening this issue as I have been struggling with the same error.

Wouldn't it be possible to fix the documentation to use the class instead of the function for configuring the module?

Thanks

**Comment by jstasiak** [comment]
Thanks for the suggestion @pdonorio, updated now.
