### ISSUE TITLE
flask_injector 0.9 doesn't work with injector 0.13.1

### ISSUE THREAD

**Issue by sxamit** [alecthomas/flask_injector#21]
injector dropped [use_annotation](https://github.com/alecthomas/injector/commit/fca50418a113e5036951a693f3becee9a8edbd1d) but flask injector still uses it.

flask injector automatically install injector 0.13.1 which causes errors

**Comment by jstasiak** [comment]
Hi, thanks for the report. 0.10 has just been released and it handles this (just note that there are some backwards incompatible changes in that release[1])

[1] https://github.com/alecthomas/flask_injector/blob/master/CHANGELOG.rst#version-0100
