### ISSUE TITLE
Route Injection doesn't work if flask application are run behind gunicorn

### ISSUE THREAD

**Issue by ahayamb** [alecthomas/flask_injector#23]
Somehow, injector fail to inject route param when flask application are run behind gunicorn

**Comment by jstasiak** [comment]
Hey,

To the best of my knowledge gunicorn makes no difference here and I've run Flask-Injector-based applications using guniconr. Can you provide a minimal code sample and steps required to reproduce the issue and describe what the issue is exactly?

**Comment by ahayamb** [comment]
Thanks for reaching me back, here is the code
```
from flask import Flask
from flask_injector import FlaskInjector
from injector import singleton, Injector, inject


class Dependency:
    def __init__(self):
        self.attr = 'dependency'


class Client:
    @inject
    def __init__(self, obj: Dependency):
        self.A = obj


def configure(binder):
    binder.bind(Dependency, to=Dependency, scope=singleton)
    binder.bind(Client, to=Client, scope=singleton)

inj = Injector(configure)
app = Flask(__name__)


@app.route('/')
def test(client: Client):
    return client.A.attr


if __name__ == '__main__':
    FlaskInjector(app=app, modules=[configure])
    app.run(host='0.0.0.0')
```

I'm using injector to inject `Client` object to the route. When I run the code via `python main.py` and hit the endpoint there is no error, but when I use gunicorn to run the code via `gunicorn --workers 4 main:app --bind :5000` I got this error message when I hit the endpoint
```
TypeError: test() missing 1 required positional argument: 'client'
```

**Comment by jstasiak** [comment]
That's quite expected, but first things first. Note that since you don't use the `inj` variable anywhere and Injector itself doesn't have side effects that matter in this context you can safely remote it as it's just noise. You're left with this:

```python
from flask import Flask
from flask_injector import FlaskInjector
from injector import singleton, inject


class Dependency:
    def __init__(self):
        self.attr = 'dependency'


class Client:
    @inject
    def __init__(self, obj: Dependency):
        self.A = obj


def configure(binder):
    binder.bind(Dependency, to=Dependency, scope=singleton)
    binder.bind(Client, to=Client, scope=singleton)

app = Flask(__name__)


@app.route('/')
def test(client: Client):
    return client.A.attr


if __name__ == '__main__':
    FlaskInjector(app=app, modules=[configure])
    app.run(host='0.0.0.0')
```

Now - `FlaskInjector(...)` is where the Flask application gets instrumented to have Injector-backed dependency injection present. You put it inside a block guarded by the `__name__ == '__main__'` condition which means it only gets executed when you run this module directly, not when you import it (and gunicorn just imports your module to get the `app` variable). You want `FlaskInjector` to instrument the Flask application regardless of how you run your application, so:

```python
from flask import Flask
from flask_injector import FlaskInjector
from injector import singleton, Injector, inject


class Dependency:
    def __init__(self):
        self.attr = 'dependency'


class Client:
    @inject
    def __init__(self, obj: Dependency):
        self.A = obj


def configure(binder):
    binder.bind(Dependency, to=Dependency, scope=singleton)
    binder.bind(Client, to=Client, scope=singleton)

app = Flask(__name__)
FlaskInjector(app=app, modules=[configure])

@app.route('/')
def test(client: Client):
    return client.A.attr


if __name__ == '__main__':
    app.run(host='0.0.0.0')
```

**Comment by ahayamb** [comment]
Thank you, it works :+1:
