### ISSUE TITLE
flask-restful is a hard dependency

### ISSUE THREAD

**Issue by yoanisgil** [alecthomas/flask_injector#24]
I'm using flask-injector==0.10.1  alone with Flask-Restplus However Flask-Restful is a hard dependecy because otherwise the following error will be thrown:

```bash
api_next_1              |   File "/usr/local/lib/python3.6/site-packages/flask_injector.py", line 65, in wrap_fun
api_next_1              |     return wrap_class_based_view(fun, injector)
api_next_1              |   File "/usr/local/lib/python3.6/site-packages/flask_injector.py", line 156, in wrap_class_based_view
api_next_1              |     return wrap_flask_restful_resource(fun, flask_restful_api, injector)
api_next_1              |   File "/usr/local/lib/python3.6/site-packages/flask_injector.py", line 171, in wrap_flask_restful_resource
api_next_1              |     from flask_restful.utils import unpack
api_next_1              | ModuleNotFoundError: No module named 'flask_restful'
```

**Comment by yoanisgil** [comment]
The problem seems to be around these lines:

https://github.com/alecthomas/flask_injector/blob/master/flask_injector.py#L83

when trying to detect if flask_restful is being used.

**Comment by jstasiak** [comment]
Can you provide a minimal code sample that triggers this?

**Comment by yoanisgil** [comment]
The resource definition goes like this:

```python
@ns.route('/', strict_slashes=False)
class UserResource(Resource):
    @inject
    def __init__(self, user_repository: UserRepository, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._user_repository = user_repository

    @api.marshal_with(list_of_users)
    def get(self) -> Dict:
        """
        Returns the list of users
        """
        return {'users': list(self._user_repository.find_all())}

```

and the application is created like this:

```python
def create_app(database_url):
    app = Flask(__name__)
    app.config.from_object('api_next.config.Config')

    JWTManager(app)

    blueprint = Blueprint('api', __name__, url_prefix='/api')
    CORS(blueprint, origins=app.config['CORS_ORIGINS'])

    api.init_app(blueprint)

    api.add_namespace(user_namespace)
    api.add_namespace(status_namespace)
    api.add_namespace(bounding_box_namespace)

    app.register_blueprint(blueprint)

    def configure(binder):
        binder.bind(UserRepository, to=UserRepository(database_url), scope=request)
        binder.bind(TagRepository, to=TagRepository(database_url), scope=request)

    FlaskInjector(app=app, modules=[configure])

    return app
```

And this is the Pipfile:

```ini
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

flask = "*"
requests = "*"
gunicorn = "*"
python-dotenv = "*"
flask-cors = "*"
flask-restplus = "*"
flask-jwt-extended = "*"
flask-injector = "*"

[dev-packages]

pytest-tornado = "*"
pytest-freezegun = "*"
pytest = "*"
pytest-coverage = "*"
pytest-flask = "*"


[requires]
python_version = "3.6"
```

Let me know if this helps. For now I just installed flask-restful and it seems to do the trick.

**Comment by Tommassino** [comment]
Ran into this aswell. Tried to go through the code and it seems it detects restplus as flask_restful. In `wrap_class_based_view` the variable `flask_restful_api` is assigned a flask_restplus.Api object.

**Comment by yoanisgil** [comment]
That is indeed the case. Maybe it should look to the instance type instead of checking the presence of *kwargs* ? @alecthomas just curious,  why do we you need to check for flask_restplus specifically?

@Tommassino installing restplus fixed the error and I have not run into any major issue this far.

**Comment by alecthomas** [comment]
Can you try master? The code looks quite different, and conditionally imports flask_restful.

**Comment by yoanisgil** [comment]
I can give it a try, but what I see here:

https://github.com/alecthomas/flask_injector/blob/master/flask_injector.py#L83

seems to be the same as in 0.10.1 (there is actually a comment on at file that refers to 0.10.1)

**Comment by yoanisgil** [comment]
I think there is:

https://github.com/alecthomas/flask_injector/blob/master/flask_injector.py#L171

Right?

**Comment by rafales** [comment]
I just ran into the same problem. I have restplus installed (without restful).

@alecthomas this is indeed an import in `wrap_flask_restful_resource` function, you can view it here: https://github.com/alecthomas/flask_injector/blob/master/flask_injector.py#L171

 Why is this needed? Should we call the same thing for restplus or just skip it for restplus?

**Comment by jstasiak** [comment]
The 0.11.0 version that's just been released addresses this issue, thank you for reporting it.
