### ISSUE TITLE
how request scope works with overrides? (it doesn't)

### ISSUE THREAD

**Issue by comtihon** [alecthomas/flask_injector#27]
Hi, 
I have:

```
@request
class A:
```
and 

```
class OverrideA(A):
```

at some point (during one request) I do:
```
override = OverrideA(some_data)
app.injector.binder.bind(A, override, scope=RequestScope)
```
I expect all other pieces of code to recieve my override instance during this request.
But `A` is still recieved.

How can I get the desired behaviour (or where should I dig to fix it)?

Thanks!

**Comment by jstasiak** [comment]
Can you provide an executable code sample that demonstrates the problem?

Note that while modifying bindings dynamically during handling of a request is technically possible it's not supported and quite likely not desired. Also it's not the binding that lives for a duration of a request but the instance of a type you're binding to - `app.injector.binder.bind(A, override, scope=RequestScope)` binds `A` to the particular instance `override` and the binding will stay there forever until you override it again.

If you want to conditionally bind `A` to something use a provider method:

```
class AModule(Module):
    @provider
    @request_scope
    def provide_a(self, ...) -> A:
        if some_condition:
            return A()
        else:
            return SomeOtherA(...)
```

**Comment by comtihon** [comment]
Yeah,
This morning I made a fresh sight on my code and decided to use provider.
Thanks!
