### ISSUE TITLE
Module as singleton?

### ISSUE THREAD

**Issue by comtihon** [alecthomas/flask_injector#28]
Hi again!
As a workaround for https://github.com/alecthomas/flask_injector/issues/27 I've decided to have some kind of factory:

```python
@singleton
class AProvider(Module):
  override = None
  def set_override(self, override: A):
     self.override = override

  @provides
  @request
  def get(self) -> A:
     if self.override is None:
        return A()
     else:
        return_me = self.override
        self.override = None
        return return_me
```
The problem is - AProvider is not always a singleton. It is singleton for all manuall requests to injector, but it uses another copy of AProvider when calling `provide` method. Thus this intent is now working.
Workaround for me is to use class.override instead on instance override. But I still expect singleton to be singleton...

```

**Comment by jstasiak** [comment]
This won't work, modules aren't managed by Injector the way other types are and putting `@singleton` there won't work. You need to do something like:

```python
@singleton
class Overrider:
    override = None
    def set_override(self, override: A):
        self.override = override

class AModule(Module):
  @provider
  @request_scope
  def provide_a(self, overrider: Overrider) -> A:
     if overrider.override is None:
        return A()
     else:
        return_me = overrider.override
        overrider.override = None
        return return_me
```

But it still doesn't look good to me, there's a race condition in this code if your application is multi-threaded and the whole "set semi-global variable for the next request to get special treatment" business seems inconvenient at best.

I don't know your code, but I suggest avoiding singletons here and, if possible, doing everything necessary in the provider method or you can decorate `Overrider` with `request_scope` and do the override at request level - that's fine too. Anything to avoid singleton-level state that trickles down to request level.

**Comment by comtihon** [comment]
Many thanks, 
I've switched to request scopes.
