### ISSUE TITLE
handling requirements of the flask app itself (not a bug, looking for suggestions)

### ISSUE THREAD

**Issue by trondhindenes** [alecthomas/flask_injector#30]
I'm trying to refactor some existing flask apps, and have stumbled into this problem that I can't seem to figure out:
Given this app (relevant parts of the "main" flask app file):
```
configuration = ConfigGetter.get_config()
logger = log.setup_custom_logger(configuration.logging_level)

from awsinventory.api_inventory import ApiInventory
from awsinventory.healthz import HealthEndpoint

def configure_dependency_injection(binder):
    binder.bind(Configuration, to=configuration, scope=singleton)
    binder.bind(AwsInventory, scope=singleton)
    if configuration.consul_enabled:
        binder.bind(ConsulHelper, scope=singleton)

FlaskInjector(app=app, modules=[configure_dependency_injection])
```
We're using a configuration object with other classes can depend on, and it works great. However, I also need the same configuration object when instantiating the flask app itself (loglevel, flask host/port, etc are all in the configuration object).

In an ideal world I would have injected the configuration class into the flask app in the same way as for AwsInventory/ConsulHelper, but since the binder takes the flask app as a parameter, that's not possible - as far as I can see the flask app needs to be instantiated before the FlaskInjector can execute. 

The result of these problems is that I'm unable to set up testing the way I want, because the flask app is still dependent on a "manually" instantiated configuration object, which means I can't just inject it during test as was my plan.

Again, this is not a bug and I totally understand it if you (maintainer) is unwilling to provide "support" like this (in that case I'll just close it).

**Comment by trondhindenes** [comment]
To partly answer myself: I guess one solution would be to call `FlaskInjector` as early as possible after the flask `app` object is instantiated, and then use injector getters to get hold of the configuration object:
```python
def configure_dependency_injection(binder):
    binder.bind(Configuration, to=ConfigGetter.get_config(), scope=singleton)
    binder.bind(AwsInventory, scope=singleton)
    binder.bind(ConsulHelper, scope=singleton)


injector = FlaskInjector(app=app, modules=[configure_dependency_injection]).injector
configuration = injector.get(Configuration)

logger = log.setup_custom_logger(configuration.logging_level)
```

**Comment by jstasiak** [comment]
> I guess one solution would be to call `FlaskInjector` as early as possible after the flask `app` object is instantiated

Instantiated *and* fully initialised (all views, hooks and handlers attached), but yes, it'll work. Let me share how I solved a similar issue in the past though. Basically I stopped creating a global Flask application at module level and switched to the following pattern[1] (I modified your example to fit):

```python

def configure_dependency_injection(binder):
    binder.bind(Configuration, to=ConfigGetter.get_config(), scope=singleton)
    binder.bind(AwsInventory, scope=singleton)
    binder.bind(ConsulHelper, scope=singleton)


def create_app(extra_injector_modules = None):
    extra_injector_modules = extra_modules or []
    injector_modules = [configure_dependency_injection, *extra_modules]
    app = Flask(...)

    # attach blueprints, views etc. here

    injector = FlaskInjector(app=app, modules=injector_modules).injector
    configuration = injector.get(Configuration)

    logger = log.setup_custom_logger(configuration.logging_level)
    return app
```

I don't know what application server you're using but it should support referring to an application object returned by a function, for example gunicorn supports this:

```
$ gunicorn 'app_module:create_app()'
```

This way not only you avoid doing too many things at import-time but it makes your life easier if you want to test the "real" Flask application, you just call `create_app()` with some extra test-specific modules. Hope this helps, I found this pattern to be useful and convenient.

[1] Attaching views can't depend on global `app` variable anymore, this makes some things (attaching handlers, context processors etc. that don't live in blueprints) inconvenient but I think it's worth it.

**Comment by trondhindenes** [comment]
nice, thank you! I'll play with that. Thanks!!
