### ISSUE TITLE
Memory leaks when exceptions thrown

### ISSUE THREAD

**Issue by mvarga6** [alecthomas/flask_injector#32]
I've injected some objects into a route that I found is commonly throwing exception.  When this occurs, the app memory usage starts to climb every time another exception is thrown.  I'm using the `@injector` decorator on the function.  I'm thinking that the objects are injected "per request" and are not being cleaned up.  Does this seem possible or expected?

**Comment by jstasiak** [comment]
Expected – no, possible – definitely. If you could check what types of objects accumulate in memory in your case that'd be helpful.

There was this case in the past for example: https://github.com/alecthomas/flask_injector/issues/9

**Comment by mvarga6** [comment]
@jstasiak Sorry for the delay (we've found work in the meantime).  I will still try to investigate what objects were accumulating. We're injecting custom objects that have a few edges of dependence. (Injecting a Client object -> Service object -> route methods).  I speculate this may be causing the gc from cleaning them up.

**Comment by jstasiak** [comment]
No worries. If you could produce a test case that would allow us to reproduce this issue it'd make debugging this that much easier but I imagine it's not trivial.

**Comment by jstasiak** [comment]
I can't reproduce this – please reopen with some additional information if it still happens in your application.
