### ISSUE TITLE
Add support for Flask-restx

### ISSUE THREAD

**Issue by michaelbukachi** [alecthomas/flask_injector#47]
`Flask-restplus` has been forked and is now actively maintained at [flask-restx](https://github.com/python-restx/flask-restx). Any plans to add support? I could do a PR.

**Comment by jstasiak** [comment]
I didn't know about the fork, but a pull request will be appreciated. :)

**Comment by michaelbukachi** [comment]
Great. On it.

**Comment by michaelbukachi** [comment]
@jstasiak How do I run tests? Can't seem to figure it out.

**Comment by jstasiak** [comment]
``make ci`` for tests + linters, otherwise ``make test`` for just tests (from https://github.com/alecthomas/flask_injector/blob/03b09d1b1173f7b2067410e749c9d37229406ea1/.travis.yml#L19)

**Comment by michaelbukachi** [comment]
Oh. Silly me. I didn't check `travis.yml`

**Comment by michaelbukachi** [comment]
Thanks for fast response. How soon can we expect the next version?

**Comment by jstasiak** [comment]
This is done now, can be closed.
