### ISSUE TITLE
before_request

### ISSUE THREAD

**Issue by davidrosenstark** [alecthomas/flask_injector#49]
Can you provide example of before_request? I have a fully working example with injection working on the routes but in the before request the injection is not using the singletons i have created in my AppModule configure function?
Thanks

**Comment by jstasiak** [comment]
There's nothing special about `before_request`, see the way it's used in the tests: https://github.com/alecthomas/flask_injector/blob/043b05183d311cbbfa693546af866d11bb0fee74/flask_injector/tests.py#L49

I can't really say anything more without knowing what exact versions of your dependencies you're using (Python, Flask-Injector, Flask, Injector) and having a piece of code that demonstrates the issue.

**Comment by davidrosenstark** [comment]
my bad. I didnt understand that the configure is called on each request thus rebinding but it will happily rebind my singletons.

**Comment by jstasiak** [comment]
There may still be some misunderstanding here. If by `configure` you mean the [`Module.configure` method](https://injector.readthedocs.io/en/latest/api.html#injector.Module.configure) then the modules are only installed and configured once, not every request. You *can* install them every request, but that's totally not supported. If you provide some minimal code it'll be easier to say if something's not right with the setup.
