### ISSUE TITLE
What is the best solution using flask-injector for dependent extensions of each other

### ISSUE THREAD

**Issue by klinkin** [alecthomas/flask_injector#5]
What is the best solution using flask-injector for dependent extensions of each other, for example flask-sqlalchemy and flask-security?

Ordinary simple code:

```python
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.security import Security, SQLAlchemyUserDatastore
from models import User, Role
 
app = Flask("super_app")
db = SQLAlchemy(app)
security = Security(app=app, datastore=SQLAlchemyUserDatastore(db, User, Role))
```

**Comment by jstasiak** [comment]
@klinkin I'll close this issue as I believe it's resolved, please reopen or comment if you have any other questions.
