### ISSUE TITLE
Enhancement: Make underlying injector accessible from library

### ISSUE THREAD

**Issue by Chratho** [alecthomas/flask_injector#52]
While integrating `Flask-Injector` I stumbled among a few cases where retrieving my injector-managed instances using dependency injection is not feasible. For example, I might have code like the following

```
@app.route("/foo")
@cost_center
def foo(db: sqlite3.Connection):
    users = db.execute('SELECT * FROM users').all()
    return render("foo.html")
``` 

where `cost_center` is some function-based decorator that measures runtime stats about the respective route and uses a `request`-scoped Stats-Collector to solve this task.

So far I think the best way to implement this is to give access to the underlying `injector` used by `Flask-Injector` itself, i.e. `injector.get(StatsCollector, scope=request)`. Since this requires the developer to manage separate access to the injector, it would be nice if `Flask-Injector` could support this use-case directly instead.

Given the current architecture, I am not sure whether there is a clean approach to this. At least I wanted to document this might be a valid use-case.

**Comment by jstasiak** [comment]
I'm not sure why is using dependency injection here not feasible. I've done it in the past using the following pattern, but maybe it's not acceptable in your case (just off the top of my head, may not run without some changes):

```python
def cost_center(function):
    @functools.wraps(function)
    def wrapper(*args, **kwargs):
        collector = kwargs.pop('__cost_center_collector')
        # use collector here
        return function(*args, **kwargs)
    # Dependency injection happens based on type hints, so if we return a wrapper with
    # an extra annotation we'll get an extra dependency injected.
    wrapper.__annotations__['__cost_center_collector'] = TheCollectorClass
    return wrapper
```

**Comment by Chratho** [comment]
Wow, it took me some moments to get what's happening here... brilliant! Thank you very much..

**Comment by jstasiak** [comment]
No worries. I'll keep in mind this may be mentioned somewhere in the documentation, could come in handy. :)
