### ISSUE TITLE
Memory leak with eventlet enabled

### ISSUE THREAD

**Issue by plumzl** [alecthomas/flask_injector#9]
I'm experiencing memory leaks when using gunicorn eventlet workers.

Some digging shows me the leak comes from GreenThread objects not being released by RequestScope.
```python
def reset(self):
    self._local_manager.cleanup()
    self._locals.scope = {}
```
Here, the `self._local_manager.cleanup()`  pops the reference to the GreenThread object but `self._locals.scope = {}` adds the reference back to the `__storage__` dictionary held by `self._locals`, so GreenThread object is not dereferenced and causing the application memory usage increase.

The problem disappears when switching the order of the two lines. Any thought?

**Comment by jstasiak** [comment]
Fixed by #11
